Controllers/CuentaController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TRABAJOFINAL.Data;
using TRABAJOFINAL.Models;
using TRABAJOFINAL.ViewModels;

namespace TRABAJOFINAL.Controllers
{
    public class CuentaController: Controller
    {
        private TrabajoFinalDbContext _context;
        private UserManager<IdentityUser> _userManager;
        private SignInManager<IdentityUser> _signInManager;

        public CuentaController(
            TrabajoFinalDbContext t,
            UserManager<IdentityUser> um,
            SignInManager<IdentityUser> sim

        ){
            _context=t;
            _userManager =um;
            _signInManager =sim;
        }
        public IActionResult Unetenos()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Unetenos(RegistroViewModel vm)
        {
            if(ModelState.IsValid){
                var user = new Usuario();
                user.UserName=vm.Usuario;
                user.Email=vm.Email;
                user.direccion=vm.direccion;
                user.telefono=vm.telefono;
                
                
                var resultado = _userManager.CreateAsync(user, vm.Password);

                if(resultado.Result==IdentityResult.Success){
                    return RedirectToAction("Index", "home");
                }else{
                    foreach(var error in resultado.Result.Errors){
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(vm);
        }

         public IActionResult IniciarSesion()
        {
            
            return View();
        }


        [HttpPost]
        public IActionResult IniciarSesion(LoginViewModel lv)
        {
            if(ModelState.IsValid){
                

                var resultado = _signInManager.PasswordSignInAsync(lv.Usuario, lv.Password, false, false);

                if(resultado.Result.Succeeded){
                    return RedirectToAction("Index", "home");
                }else{
                    
                        ModelState.AddModelError("", "Error en contraseña o usuario");
                    
                }
            }
            return View(lv);
        }

        public IActionResult CerrarSesion()
        {
          _signInManager.SignOutAsync();
          return RedirectToAction("Index", "home");
        }
    }
}

Controllers/MascotaController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TRABAJOFINAL.Data;
using TRABAJOFINAL.Models;

namespace TRABAJOFINAL.Controllers
{
    public class MascotaController:Controller
    {
      TrabajoFinalDbContext _con;

      public MascotaController(TrabajoFinalDbContext tr){
        _con=tr;

      }
        public IActionResult Mascotas()
        {
            return View();
        }
        
        public IActionResult Esterilizacion()
        {
         
          return View();
        }
        [HttpPost]
        public IActionResult Esterilizacion(Mascota masc)
        {
          if(ModelState.IsValid){
            var user = _con.Usuarios.FirstOrDefault(x=> x.UserName == User.Identity.Name);
            masc.usuarioId=user.Id;
                if(masc.categoria!="SEXO"){
                   masc.estado="Para proceso de esterilización";
                    _con.Mascota.Add(masc);
                    _con.SaveChanges();
                    return RedirectToAction("ProcesoEsterilizacion");
                }else
                {
                  
                  return RedirectToAction("Esterilizacion");
                }
            }
          
          return View(masc);
        }
        public IActionResult ProcesoEsterilizacion()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }

        public IActionResult Adoptar()
        {
          var mascotas= _con.Mascota.Where(X=> X.estado=="En adopcion").ToList();
          return View(mascotas);
        }
        
        [HttpPost]
        public IActionResult Adoptar(int id)
        {
          var mascota = _con.Mascota.Find(id);
          mascota.estado="En proceso de adopción";
          _con.SaveChanges();
          return RedirectToAction("ValidarAdopcion");
        }
       public IActionResult validarAdopcion()
       {
         //TODO: Implement Realistic Implementation
         return View();
       }
        

        
        public IActionResult MascotasRescatadas()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        [HttpPost]
        public IActionResult MascotasRescatadas(Mascota masc)
        {
           if(ModelState.IsValid){
             
                if(masc.categoria!="SEXO"){
                    masc.estado="Mascota rescatada; esperando diagnostico";
                    _con.Mascota.Add(masc);
                    _con.SaveChanges();
                    return RedirectToAction("ListaMascota");
                }else
                {
                  
                  return RedirectToAction("MascotasRescatadas");
                }
            }
            
        
          return View(masc);
        }
        public IActionResult DarAdopcion()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        [HttpPost]
        public IActionResult DarAdopcion(Mascota masc)
        {
          
           if(ModelState.IsValid){
              var user = _con.Usuarios.FirstOrDefault(x=> x.UserName == User.Identity.Name);
              masc.usuarioId=user.Id;
                if(masc.categoria!="SEXO"){
                    masc.estado="Espera para ser adoptado";
                    _con.Mascota.Add(masc);
                    _con.SaveChanges();
                    return RedirectToAction("GraciasDarAdopcion");
                }else
                {
                  
                  return RedirectToAction("DarAdopcion");
                }
            }
            
        
          return View(masc);
        }
        public IActionResult GraciasDarAdopcion()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }

        public IActionResult ListaMascota()
        {
          
         
          var mascotas= _con.Mascota.ToList();
          return View(mascotas);
        }

        public IActionResult Actualizar(int id)
        {
            var p = _con.Mascota.FirstOrDefault(x => x.id == id);
            

            if (p == null) {
                return NotFound();
            }

            return View(p);
        }

        [HttpPost]
        public IActionResult Actualizar(Mascota m)
        {
            if (ModelState.IsValid) {
              if(m.estado!="estado"){
                    var mascot = _con.Mascota.Find(m.id);
                    mascot.estado = m.estado;
                    _con.SaveChanges();
                    return RedirectToAction("ListaMascota");
                }else
                {
                  
                  return RedirectToAction("Actualizar");
                }
            }

            return View(m);
        }

        public IActionResult Borrar(int id)
        {
            var p = _con.Mascota.FirstOrDefault(x => x.id == id);

            if (p != null) {
                _con.Mascota.Remove(p);
                _con.SaveChanges();
            }

            return RedirectToAction("ListaMascota");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PETBienestar</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-image: url(http://www.wuf.pe/assets/img/bloq4.jpg">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://cdn.pixabay.com/photo/2016/03/31/17/37/animal-1293792_960_720.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    PETBienestar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                            
                            @if (Context.User.Identity.IsAuthenticated  && Context.User.Identity.Name=="AdminPETBienestar") {
                         
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">INICIO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Nosotros">NOSOTROS</a>
                        </li> 
              
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MASCOTA" asp-action="ListaMascota">LISTA DE MASCOTAS</a>
                            </li>

                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HOME" asp-action="ListaSugerencias">LISTA DE SUGERENCIAS</a>
                            </li>

                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mascota" asp-action="MascotasRescatadas">INGRESAR NUEVA MASCOTA RESCATADA</a>
                            </li>

                            
                            
                            
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="CerrarSesion">Cerrar sesión</a>
                            </li>


                        }else if(Context.User.Identity.IsAuthenticated){
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">INICIO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Nosotros">NOSOTROS</a>
                        </li> 
                        
                         
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sugerencias">SUGERENCIAS</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mascota" asp-action="Mascotas">MASCOTAS</a>
                            </li>

                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Alertas">ALERTAS</a>
                            </li>


                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HOME" asp-action="Donaciones">DONACION</a>
                            </li>

                            
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="CerrarSesion">Cerrar sesión</a>
                            </li>

                            
                        }
                        else {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">INICIO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Nosotros">NOSOTROS</a>
                        </li> 
                        
                         
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sugerencias">SUGERENCIAS</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Unetenos">UNETENOS</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HOME" asp-action="Donaciones">DONACION</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="IniciarSesion">INICIAR SESION</a>
                            
                        </li> 

                        }
                        
                         
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @RenderBody()


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PETBienestar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>